spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BROKERS:localhost:9092}
      bindings:
        producer-out-0:
          destination: event-topic
        consumer-in-0:
          destination: event-topic
          group: ${spring.application.name}-group
