spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST:localhost}:27017/${DB_NAME:starterdb}
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
