spring:
  datasource:
    url: jdbc:oracle:thin:@${DB_HOST:localhost}:1521:${DB_SID:xe}
    username: ${DB_USER:system}
    password: ${DB_PASS:oracle}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
