package com.common.starter.security.abstraction;

import java.util.Map;

/**
 * Generic interface for token operations.
 * Provides abstraction over different token implementations (JWT, OAuth2,
 * custom tokens).
 * 
 * @param <T> The type of claims/payload contained in the token
 */
public interface TokenProvider<T> {

    /**
     * Generates a token for the given subject with optional additional claims.
     *
     * @param subject          The subject (typically username or user ID) for the
     *                         token
     * @param additionalClaims Additional claims to include in the token
     * @return The generated token string
     */
    String generateToken(String subject, Map<String, Object> additionalClaims);

    /**
     * Generates a token for the given subject with default claims.
     *
     * @param subject The subject (typically username or user ID) for the token
     * @return The generated token string
     */
    default String generateToken(String subject) {
        return generateToken(subject, Map.of());
    }

    /**
     * Validates the given token.
     *
     * @param token The token to validate
     * @return true if the token is valid, false otherwise
     */
    boolean validateToken(String token);

    /**
     * Extracts the subject (username/user ID) from the token.
     *
     * @param token The token to extract from
     * @return The subject contained in the token
     */
    String extractSubject(String token);

    /**
     * Extracts all claims from the token.
     *
     * @param token The token to extract claims from
     * @return The claims contained in the token
     */
    T extractClaims(String token);

    /**
     * Checks if the token has expired.
     *
     * @param token The token to check
     * @return true if the token has expired, false otherwise
     */
    boolean isTokenExpired(String token);

    /**
     * Gets the expiration time in milliseconds for tokens generated by this
     * provider.
     *
     * @return The expiration time in milliseconds
     */
    long getExpirationTime();
}
