image: maven:3.9.6-eclipse-temurin-21

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - mvn compile

test:
  stage: test
  script:
    - mvn test

docker-build:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t my-registry/microservice-starter:$CI_COMMIT_SHA .
    - docker push my-registry/microservice-starter:$CI_COMMIT_SHA
  only:
    - main
